### ISSUE TITLE
Links to things

### ISSUE THREAD

**Issue by renespeck** [dice-group/AGDISTIS#45]
Agdistis links `Mcnabb Inc` to `dbr:McNabb` that is of type `Thing` in DBpedia.

**Comment by DiegoMoussallem** [comment]
I'll have a look on this problem. As a way to alleviate this problem, you can set the agidists.properties file for only accepting Named Entity (Person, Org and Location) instead of accepting common types. Could you see if it alleviates for a while?

**Comment by renespeck** [comment]
Ohh, nice. Could you tell me the `key` I have to use for the `values` of the Named Entity Types in the agidists.properties please?

**Comment by DiegoMoussallem** [comment]
#Enable to find common entities
commonEntities=false

false for finding only Named Entities and true for finding every kind of them

**Comment by renespeck** [comment]
Ahh thanks. :+1:

**Comment by renespeck** [comment]
Hi, changing 'commonEntities' value to 'true'  had no influence of the linking. 

Agdistis still links `Mcnabb Inc` to `dbr:McNabb`.

**Comment by DiegoMoussallem** [comment]
Could you write the sentence here? and I will find the bug/problem. :)

**Comment by renespeck** [comment]
`Jim Mcnabb Inc is in the Outdoor Advertising Services industry in Taylor, TX. This company currently has approximately 5 to 10 employees and annual sales of $1,000,000 to $4,999,999.`

**Comment by DiegoMoussallem** [comment]
Our corporation affixes list comprises of 
'corp
Corp
ltd
Ltd
inc
Inc
co
Co' 

So, AGDISTIS cleans the label using these affixes, Mcnabb Inc becomes only Mcnabb, however this label is quite generic where our filter of disambiguation pages does not work. I assume it is a bug and I will have a look into more details. I come to you as soon as possible.

**Comment by DiegoMoussallem** [comment]
Hi @renespeck ,

Apologizes for this late response, I figured out the bug. It has happened because of redirect's method was skipping the verification of disambiguation's page. Therefore, when AGDISTIS was receiving ''McNabb Inc'', it was removing ''dbr:McNabb'', however, dbr:Mcnabb was also a candidate which has been redirecting to ''dbr:McNabb'' then resulting in that mistake. I fixed this little bug and you can check by downloading the master branch again. 

pls, close the issue after your verification.

**Comment by renespeck** [comment]
Thanks for the fix, seems to work. :D
