### ISSUE TITLE
German DBpedia 2016-10

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/AGDISTIS#47]
Using the following sentence:
`<entity>Angela Merkel</entity> was in <entity>Germany</entity>`
```
AGDISTIS returns the following in FOX:
scms:means http://de.dbpedia.org/resource/Angela_Merici ;
scms:source source:fox ;
ann:body "Angela Merkel"^^xsd:string
scms:means http://de.dbpedia.org/resource/Germany_Schulz ;
scms:source source:fox ;
ann:body "Germany"^^xsd:string
```

Please fix that and write a unit test for it.

**Comment by RicardoUsbeck** [comment]
With the latest version the outcome is:

```
curl --data-urlencode "text='<entity>Angela Merkel</entity> was in <entity>Germany</entity>'" -d type='agdistis' http://localhost:8080/AGDISTIS

[{"disambiguatedURL":"http:\/\/de.dbpedia.org\/resource\/Angela_Merkel","offset":13,"namedEntity":"Angela Merkel","start":1},{"disambiguatedURL":"http:\/\/de.dbpedia.org\/resource\/Germany_(Pennsylvania)","offset":7,"namedEntity":"Germany","start":22}]
```

**Comment by DiegoMoussallem** [comment]
Question: Why should AGDISTIS be able to disambiguate "Germany" in the German version as the correct name is "Deutschland"?

Bug: AGDISTIS is not able to disambiguate "Germany" because  "Germany" does not appear as a country neither in German DBpedia nor [Wikipedia](https://de.wikipedia.org/wiki/Germany). It is a disambiguation page in both which actually points to many resources but none of them is the country. See:

`<http://de.dbpedia.org/resource/Germany http://dbpedia.org/ontology/wikiPageDisambiguates http://de.dbpedia.org/resource/Germany_(Mondkrater)>
<http://de.dbpedia.org/resource/Germany http://dbpedia.org/ontology/wikiPageDisambiguates http://de.dbpedia.org/resource/Italo_Reno_&_Germany>
<http://de.dbpedia.org/resource/Germany http://dbpedia.org/ontology/wikiPageDisambiguates http://de.dbpedia.org/resource/Germany_(Georgia)>
<http://de.dbpedia.org/resource/Germany http://dbpedia.org/ontology/wikiPageDisambiguates http://de.dbpedia.org/resource/Germany_(Indiana)>
<http://de.dbpedia.org/resource/Germany http://dbpedia.org/ontology/wikiPageDisambiguates http://de.dbpedia.org/resource/Germany_(Pennsylvania)>
<http://de.dbpedia.org/resource/Germany http://dbpedia.org/ontology/wikiPageDisambiguates http://de.dbpedia.org/resource/Germany_(Texas)>
<http://de.dbpedia.org/resource/Germany http://dbpedia.org/ontology/wikiPageDisambiguates http://de.dbpedia.org/resource/Germany_Schaefer>
<http://de.dbpedia.org/resource/Germany http://dbpedia.org/ontology/wikiPageDisambiguates http://de.dbpedia.org/resource/Germany_Schulz>
<http://de.dbpedia.org/resource/Germany http://dbpedia.org/ontology/wikiPageDisambiguates http://de.dbpedia.org/resource/Germany_Smith>
<http://de.dbpedia.org/resource/Germany http://dbpedia.org/ontology/wikiPageDisambiguates http://de.dbpedia.org/resource/Jim_Germany>
<http://de.dbpedia.org/resource/Germany http://dbpedia.org/ontology/wikiPageDisambiguates http://de.dbpedia.org/resource/Reggie_Germany>
<http://de.dbpedia.org/resource/Germany http://dbpedia.org/ontology/wikiPageDisambiguates http://de.dbpedia.org/resource/Willie_Germany>
<http://de.dbpedia.org/resource/Germany http://dbpedia.org/ontology/wikiPageDisambiguates http://de.dbpedia.org/resource/Made_in_Germany>
` 

Additionally, `http://de.dbpedia.org/resource/Deutschland` does not contain any label as "Germany". 

Although, our search by context shows `dbr:Deutschland` as a possible candidate, it fails because there is not any similarity with Germany.

Finally, I thought quite interesting this issue.

**Comment by RicardoUsbeck** [comment]
Well but you are right, the endpoint and task are mixed up => won't fix
