### ISSUE TITLE
Clarify index2 naming in config

### ISSUE THREAD

**Issue by yamalight** [dice-group/AGDISTIS#56]
Currently in config we have two following fields:
```
index=index
index2=index_bycontext
```

From name it is not clear what is `index2` and how it's used.
I'd suggest doing the following:

- [x] (short term) add comment to config file clarifying what it does
- [x] (long term) rename it to reflect its role

**Comment by DiegoMoussallem** [comment]
improved with the new commit.

**Comment by yamalight** [comment]
@DiegoMoussallem looks like this broke tests: https://gitlab.com/aksw/AGDISTIS/-/jobs/53308720

**Comment by DiegoMoussallem** [comment]
I thought the problem was the one pointed by Ricardo above then I fixed it which was from indextest to index again in property files. But the error still appears. Do you have any tip @yamalight ? because If you download the code e run by maven it works and delivers the same results expected by test-docker.sh.

**Comment by DiegoMoussallem** [comment]
Seems that https://gitlab.com/aksw/AGDISTIS/commits/master takes time to mirror the commits. lets see

**Comment by DiegoMoussallem** [comment]
everything is ok now

**Comment by yamalight** [comment]
looks good, thanks! 👍
