### ISSUE TITLE
In BFS the findNode is not used (nodes always added even if already exists)

### ISSUE THREAD

**Issue by khaledadel19** [dice-group/AGDISTIS#71]
Line 49 in BreadthFirstSearch checks for the existence of targetNode in findNode. However the key used in findNode is targetNode.getObject(). 
Same for line 50 in findeNode.get().

**Comment by RicardoUsbeck** [comment]
Thanks for pointing out that issue. It is indeed good, that this if never worked from the beginning six years ago!

It is a bug!

We should remove 	`private static HashMap<String, Node> findNode = new HashMap<String, Node>();` completely from the class as this static hashmap screws up things when using two graphs.

**Comment by DiegoMoussallem** [comment]
The nodes are always added indeed, however, it does not affect AGDISTIS's performance because of the hashmap used in `edu.uci.ics.jung.graph.DirectedSparseGraph;` replaces and not duplicates when the same node is assigned to the graph. We can do what you suggested @RicardoUsbeck , because this "static" will screw up certainly when two graphs are in the game, but we can also fix it and check if we have some gain in terms of time-performance.  We could try both options.

**Comment by khaledadel19** [comment]
Thanks for your swift responses, I actually tried to activate this part. I noted that activating this check using static, causes issues even when working with only one graph, changes on the weights from one request (during HITS) affects the consequent requests if the same node is found.

**Comment by RicardoUsbeck** [comment]
Yes, that is why I would remove this HashMap and just keep the else part

**Comment by vdanielupb** [comment]
should be fixed now.

**Comment by RicardoUsbeck** [comment]
Can someone, maybe @DiegoMoussallem make sure we get the same results as in the latest MAG paper?

**Comment by DiegoMoussallem** [comment]
Sure, I am going to check it and let you know. ;)

**Comment by DiegoMoussallem** [comment]
Checked, the same results are obtained with this commit.
